### ISSUE TITLE
Can this code running on CUDA 10.0?

### ISSUE THREAD

**Issue by WingsleyLui** [yanxp/MetaR-CNN#41]
Dear author, thank you for sharing the code. I follow the instruction as the readme file except that my CUDA version is 10.0. I encountered an error as follows:
**Traceback (most recent call last):
  File "train_metarcnn.py", line 27, in <module>
    from model.utils.net_utils import weights_normal_init, save_net, load_net, \
  File "/.../MetaR-CNN/lib/model/utils/net_utils.py", line 8, in <module>
    from model.roi_crop.functions.roi_crop import RoICropFunction
  File "/.../MetaR-CNN/lib/model/roi_crop/functions/roi_crop.py", line 4, in <module>
    from .._ext import roi_crop
  File "/.../MetaR-CNN/lib/model/roi_crop/_ext/roi_crop/__init__.py", line 3, in <module>
    from ._roi_crop import lib as _lib, ffi as _ffi
ImportError: /.../MetaR-CNN/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: __cudaPopCallConfiguration**

Is that caused by the mismatched cuda version?

**Comment by tooHotSpot** [comment]
I have used Colaboratory confiuration (Tesla K80 or P100 GPUs with CUDA 10), but encountered similar issue:

```
Traceback (most recent call last):
  File "test_metarcnn.py", line 27, in <module>
    from model.nms.nms_wrapper import nms
  File "/content/MetaR-CNN/lib/model/nms/nms_wrapper.py", line 10, in <module>
    from model.nms.nms_gpu import nms_gpu
  File "/content/MetaR-CNN/lib/model/nms/nms_gpu.py", line 4, in <module>
    from ._ext import nms
  File "/content/MetaR-CNN/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
    from ._nms import lib as _lib, ffi as _ffi
ImportError: /content/MetaR-CNN/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaRegisterFatBinaryEnd
```

**Comment by Lemonqinnn** [comment]
Did you solve this problem？ I meet similar issue

**Comment by tooHotSpot** [comment]
@Lemonqinnn It would be great to solve this issue in the nearest future. I have some ideas about launching docker image with CUDA 8 directly inside the Colab env. Since everything could be launched  in CLI it seems a probable variant.

**Comment by WingsleyLui** [comment]
A CUDA version of 9.0 or 9.2 works for this code. The problem encountered by CUDA10.0 remains unsolved. @Lemonqinnn @tooHotSpot

**Comment by NHW2017** [comment]
> A CUDA version of 9.0 or 9.2 works for this code. The problem encountered by CUDA10.0 remains unsolved. @Lemonqinnn @tooHotSpot

I tried to run the program under the environment of ubuntu18.04 cuda9.2 2080ti, but it didn’t succeed. The error message is
"Found GPU0 GeForce RTX 2080 Ti which requires CUDA_VERSION >= 9000 for optimal performance and fast startup time, but your PyTorch was compiled with CUDA_VERSION 8000. Please install the correct PyTorch binary using instructions from http://pytorch.org warnings.warn( incorrect_binary_warn% (d, name, 9000, CUDA_VERSION))"
Can you tell me your environment configuration?

**Comment by Leiwx52** [comment]
> > A CUDA version of 9.0 or 9.2 works for this code. The problem encountered by CUDA10.0 remains unsolved. @Lemonqinnn @tooHotSpot
> 
> I tried to run the program under the environment of ubuntu18.04 cuda9.2 2080ti, but it didn’t succeed. The error message is
> "Found GPU0 GeForce RTX 2080 Ti which requires CUDA_VERSION >= 9000 for optimal performance and fast startup time, but your PyTorch was compiled with CUDA_VERSION 8000. Please install the correct PyTorch binary using instructions from http://pytorch.org warnings.warn( incorrect_binary_warn% (d, name, 9000, CUDA_VERSION))"
> Can you tell me your environment configuration?

hi @NHW2017 ! Sorry for my late response.

Apologize for being unable to tell you the detailed environment configs because I've left the Institute where I've been before and therefore I have no access to the GPU server by now. However, based on your description, I think the point is that your cuda driver is not compatible with your GPU, or it is not compatible with your Pytorch version. As is indicated in the message, this GPU requires CUDA_VERSION>=9000 to work well. Thus, you may update your Nvidia driver to a new version.

Hope it can help.

**Comment by hanhao2019102935** [comment]
> I have used Colaboratory configuration (Tesla K80 or P100 GPUs with CUDA 10), but encountered similar issue:
> 
> ```
> Traceback (most recent call last):
>   File "test_metarcnn.py", line 27, in <module>
>     from model.nms.nms_wrapper import nms
>   File "/content/MetaR-CNN/lib/model/nms/nms_wrapper.py", line 10, in <module>
>     from model.nms.nms_gpu import nms_gpu
>   File "/content/MetaR-CNN/lib/model/nms/nms_gpu.py", line 4, in <module>
>     from ._ext import nms
>   File "/content/MetaR-CNN/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
>     from ._nms import lib as _lib, ffi as _ffi
> ImportError: /content/MetaR-CNN/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaRegisterFatBinaryEnd
> ```



> I have used Colaboratory configuration (Tesla K80 or P100 GPUs with CUDA 10), but encountered similar issue:
> 
> ```
> Traceback (most recent call last):
>   File "test_metarcnn.py", line 27, in <module>
>     from model.nms.nms_wrapper import nms
>   File "/content/MetaR-CNN/lib/model/nms/nms_wrapper.py", line 10, in <module>
>     from model.nms.nms_gpu import nms_gpu
>   File "/content/MetaR-CNN/lib/model/nms/nms_gpu.py", line 4, in <module>
>     from ._ext import nms
>   File "/content/MetaR-CNN/lib/model/nms/_ext/nms/__init__.py", line 3, in <module>
>     from ._nms import lib as _lib, ffi as _ffi
> ImportError: /content/MetaR-CNN/lib/model/nms/_ext/nms/_nms.so: undefined symbol: __cudaRegisterFatBinaryEnd
> ```

I used Colaboratory to test this code, at first I encountered the same problem with you, then I changed the default cuda10 to cuda9.0,but RuntimeError occurred: CUDNN_STATUS_EXECUTION_FAILED.Have you now completed the code?If so, could you tell me about your configuration environment and what I should do about it？ @tooHotSpot

**Comment by hanhao2019102935** [comment]
> @Lemonqinnn Not yet, but it would be great to solve this issue in the nearest future. I have some ideas about launching docker image with CUDA 8 directly inside the Colab env. Since everything could be launched in CLI it seems a probable variant.

I used Colaboratory to test this code, at first I encountered the same problem with you, then I changed the default cuda10 to cuda9.0,but RuntimeError occurred: CUDNN_STATUS_EXECUTION_FAILED.Have you now completed the code?If so, could you tell me about your configuration environment and what I should do about it？ @tooHotSpot

**Comment by qinzhengmei** [comment]
> A CUDA version of 9.0 or 9.2 works for this code. The problem encountered by CUDA10.0 remains unsolved. @WingsleyLui 

Thank you very much for your work and I was wondering if the PyTorch version will also need to be changed when running on Cuda9.0
